version: "3.4"
services:
  kps:
      image: kps
      container_name: kps
      build: /path/to/kps
      restart: unless-stopped
      depends_on:
          - pgsql
          - redis
      ports:
        - "8000:8000"
      volumes:
        - /path/to/kps_envfile:/app/kps/.env
      environment:
        - DJANGO_SETTINGS_MODULE=kps.settings
  pgsql:
      image: postgres:latest
      container_name: pgsql
      restart: unless-stopped
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=kps
        - POSTGRES_PASSWORD=<change me>
      volumes:
        - /path/to/pgsql_data:/var/lib/postgresql/data
  redis:
      image: redis:latest
      container_name: redis
      restart: unless-stopped
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - "6379:6379"
      volumes:
        - /path/to/redis.conf:/usr/local/etc/redis/redis.conf
        - /path/to/redis_data:/data
