# Generated by Django 3.1.4 on 2020-12-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAuthor',
            fields=[
                ('userid', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
                ('avatar', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StreamComment',
            fields=[
                ('message_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=200)),
                ('message_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('action_type', models.CharField(max_length=50)),
                ('relative_time', models.DurationField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.commentauthor')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.stream')),
            ],
        ),
    ]
