# Generated by Django 3.1.4 on 2020-12-30 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentAuthor',
            new_name='Channel',
        ),
        migrations.RenameField(
            model_name='streamcomment',
            old_name='author',
            new_name='channel',
        ),
    ]
