# Generated by Django 3.1.4 on 2020-12-30 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20201230_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='channel',
            field=models.ForeignKey(default='nieuseridlasijdal', on_delete=django.db.models.deletion.CASCADE, to='charts.channel'),
            preserve_default=False,
        ),
    ]
