# Generated by Django 3.1.4 on 2020-12-31 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_stream_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamcomment',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='charts.stream'),
        ),
    ]
