# Generated by Django 3.1.4 on 2020-12-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20201231_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='userid',
            new_name='user_id',
        ),
    ]
