# Generated by Django 3.1.5 on 2021-01-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_auto_20201231_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamcomment',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='streamcomment',
            name='message_type',
        ),
    ]
