# Generated by Django 3.1.5 on 2021-01-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_auto_20210105_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamcomment',
            name='message',
            field=models.CharField(max_length=350),
        ),
    ]
